/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Document settings");
gchar *s = N_("Choose paper size");
gchar *s = N_("A4\n"
              "");
gchar *s = N_("Paper size:");
gchar *s = N_("Custom paper");
gchar *s = N_("Set page width");
gchar *s = N_("Set page height");
gchar *s = N_("Units:");
gchar *s = N_("Choose unit system");
gchar *s = N_("Millimeters\n"
              "");
gchar *s = N_("Width:");
gchar *s = N_("Height:");
gchar *s = N_("Page");
