/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Alignment base");
gchar *s = N_("Align");
gchar *s = N_("Align objects to horizontal mid");
gchar *s = N_("Align outside object to right border");
gchar *s = N_("Align inside object to right border");
gchar *s = N_("Align inside object to left border");
gchar *s = N_("Align outside object to left border");
gchar *s = N_("Align objects to vertical mid");
gchar *s = N_("Align inside object to top border");
gchar *s = N_("Align inside object to bottom border");
gchar *s = N_("Align outside object to bottom border");
gchar *s = N_("Align outside object to top border");
gchar *s = N_("Last selected\n"
              "First selected\n"
              "Biggest item\n"
              "Smallest item\n"
              "Page\n"
              "Drawing\n"
              "Selection\n"
              "");
