/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Width");
gchar *s = N_("Stroke width");
gchar *s = N_("pixels\n"
              "millimeters\n"
              "points\n"
              "inches\n"
              "");
gchar *s = N_("Scale with image");
gchar *s = N_("Join");
gchar *s = N_("bevel");
gchar *s = N_("round");
gchar *s = N_("miter");
gchar *s = N_("Cap");
gchar *s = N_("butt");
gchar *s = N_("round");
gchar *s = N_("sqare");
gchar *s = N_("General");
gchar *s = N_("Valige v\344rv");
gchar *s = N_("Stroke color");
gchar *s = N_("Is stroked");
gchar *s = N_("Behind fill");
gchar *s = N_("Stroke");
gchar *s = N_("Fill");
