/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Sodipodi");
gchar *s = N_("_File");
gchar *s = N_("_New");
gchar *s = N_("_Open");
gchar *s = N_("_Quit");
gchar *s = N_("_Help");
gchar *s = N_("_About ...");
gchar *s = N_("Drawing context");
gchar *s = N_("Edit nodes");
gchar *s = N_("Zoom in");
gchar *s = N_("Draw rectangle");
gchar *s = N_("Draw ellipse");
gchar *s = N_("Draw freehand line");
gchar *s = N_("Draw text");
gchar *s = N_("Edit nodes");
gchar *s = N_("Zoom");
gchar *s = N_("10%\n"
              "25%\n"
              "50%\n"
              "75%\n"
              "100%\n"
              "150%\n"
              "200%\n"
              "300%\n"
              "500%\n"
              "");
gchar *s = N_("Select zoom factor");
gchar *s = N_("100%");
gchar *s = N_("Zoom out");
gchar *s = N_("Zoom in");
gchar *s = N_("Zoom to drawing");
gchar *s = N_("Zoom to selection");
gchar *s = N_("Zoom to 1:1");
gchar *s = N_("Zoom to page");
gchar *s = N_("Selection");
gchar *s = N_("lower selection to bottom");
gchar *s = N_("Raise selection to top");
gchar *s = N_("Lower selection one layer");
gchar *s = N_("Rise selection one layer");
gchar *s = N_("Break apart selected paths");
gchar *s = N_("Combine selected paths");
gchar *s = N_("Group selected objects");
gchar *s = N_("Ungroup selected objects");
gchar *s = N_("Node Edit");
gchar *s = N_("Include one node into selected segments");
gchar *s = N_("Delete selected nodes");
gchar *s = N_("Convert selected segments to lines");
gchar *s = N_("Convert selected segments to curves");
gchar *s = N_("Break apart selected node");
gchar *s = N_("Join 2 selected endpoints");
gchar *s = N_("Cusp line at selected nodes");
gchar *s = N_("Smooth line at selected nodes");
gchar *s = N_("Symmetric ");
gchar *s = N_("Unsymmetric");
gchar *s = N_("Close dialog");
gchar *s = N_("File");
gchar *s = N_("New drawing");
gchar *s = N_("Export");
gchar *s = N_("Open new drawing");
gchar *s = N_("Import ");
gchar *s = N_("Print drawing");
gchar *s = N_("Preview print drawing");
gchar *s = N_("Save drawing ");
gchar *s = N_("Save drawing under new filename");
gchar *s = N_("Quit or not quit ?");
gchar *s = N_("Yes quick! I want to leave sodipodi and come back later.");
gchar *s = N_("Yep !");
gchar *s = N_("No I'd rather do some more cool vector drawing with sodipodi.");
gchar *s = N_("Nope !");
gchar *s = N_("Really wanna quit sodipodi ?");
gchar *s = N_("Object");
gchar *s = N_("Align dialog");
gchar *s = N_("Transformation dialog");
gchar *s = N_("Edit font style of selected objects");
gchar *s = N_("Edit layout of selected objects");
gchar *s = N_("Edit fill style of selected objects");
gchar *s = N_("Edit stroke style of selected objects");
gchar *s = N_("Flip selected objects");
gchar *s = N_("Rotate selected objects 90\260 clockwise");
gchar *s = N_("Remove transformation");
gchar *s = N_("Convert selected objects to curves");
gchar *s = N_("Edit");
gchar *s = N_("Undo ");
gchar *s = N_("Redo");
gchar *s = N_("Delete selection");
gchar *s = N_("Paste from clipboard");
gchar *s = N_("Copy selection to clipboard");
gchar *s = N_("Cut selection");
gchar *s = N_("Duplicate selection");
