/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Transform selection");
gchar *s = N_(" Move ");
gchar *s = N_("horizontal");
gchar *s = N_("vertical");
gchar *s = N_("move relative in");
gchar *s = N_("pixel\n"
              "points\n"
              "millimeter\n"
              "centimeter\n"
              "inch\n"
              "");
gchar *s = N_("Move");
gchar *s = N_(" Rotate ");
gchar *s = N_("90°");
gchar *s = N_("180°");
gchar *s = N_("270°");
gchar *s = N_("any");
gchar *s = N_("degree");
gchar *s = N_("right");
gchar *s = N_("left");
gchar *s = N_("Rotate");
gchar *s = N_(" Scale ");
gchar *s = N_("horizontal");
gchar *s = N_("vertical");
gchar *s = N_("% ");
gchar *s = N_("% ");
gchar *s = N_(" flip ");
gchar *s = N_(" flip ");
gchar *s = N_("Scale");
gchar *s = N_(" Skew ");
gchar *s = N_("horizontal");
gchar *s = N_("vertical");
gchar *s = N_("%  ");
gchar *s = N_("%  ");
gchar *s = N_("Skew");
gchar *s = N_("make copy");
gchar *s = N_("Guidelines setup");
gchar *s = N_("move horizontal");
gchar *s = N_("move vertical");
gchar *s = N_("pixel\n"
              "points\n"
              "millimeter\n"
              "centimeter\n"
              "inch\n"
              "");
gchar *s = N_("Snap to guides");
gchar *s = N_("Start transformation");
gchar *s = N_("close dialog");
