/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("XML Tree");
gchar *s = N_("Hierarchy");
gchar *s = N_("Dup");
gchar *s = N_("New");
gchar *s = N_("Cut");
gchar *s = N_("Copy");
gchar *s = N_("Paste");
gchar *s = N_("Del");
gchar *s = N_("Attributes");
gchar *s = N_("Key");
gchar *s = N_("Value");
gchar *s = N_("Delete");
gchar *s = N_("Add");
gchar *s = N_("Change");
gchar *s = N_("Content");
gchar *s = N_("Change");
gchar *s = N_("Change Attribute");
gchar *s = N_("Value:");
gchar *s = N_("Attribute:");
gchar *s = N_("name");
gchar *s = N_("Add attribute");
gchar *s = N_("Value:");
gchar *s = N_("Attribute:");
gchar *s = N_("Delete attribute");
gchar *s = N_("Do you want to delete attribute?");
gchar *s = N_("Attribute:");
gchar *s = N_("name");
gchar *s = N_("Value");
