#define __PREFERENCES_SKELETON_H__

static const char preferences_skeleton[] =
"<sodipodi version=\"" VERSION "\">\n"
"  <interface id=\"toolboxes\">\n"
"    <interface id=\"file\" state=\"1\"/>\n"
"    <interface id=\"edit\" state=\"1\"/>\n"
"    <interface id=\"object\" state=\"1\"/>\n"
"    <interface id=\"selection\" state=\"0\"/>\n"
"    <interface id=\"draw\" state=\"1\"/>\n"
"    <interface id=\"zoom\" state=\"0\"/>\n"
"    <interface id=\"node\" state=\"0\"/>\n"
"  </interface>\n"
"  <group id=\"tools\""
"         style=\"fill:gray;fill-opacity:1;fill-rule:evenodd;\n"
"                 stroke:black;stroke-opacity:1;stroke-width:1pt;stroke-linejoin:miter;stroke-linecap:butt;\">\n"
"    <group id=\"shapes\" style=\"stroke:none;\">\n"
"      <eventcontext id=\"rect\"/>\n"
"      <eventcontext id=\"arc\"/>\n"
"      <eventcontext id=\"star\" magnitude=\"5\"/>\n"
"      <eventcontext id=\"spiral\" style=\"fill:none;stroke:black;\"/>\n"
"    </group>\n"
"    <group id=\"freehand\""
"         style=\"fill:none;stroke:black;stroke-opacity:1;stroke-width:1pt;stroke-linejoin:miter;stroke-linecap:butt;\">\n"
"      <eventcontext id=\"pencil\"/>\n"
"      <eventcontext id=\"pen\" mode=\"drag\"/>\n"
"    </group>\n"
"    <eventcontext id=\"calligraphic\" style=\"fill:black;fill-rule:nonzero;stroke:none;\""
"                       mass=\"0.3\" drag=\"0.5\" angle=\"30\" width=\"0.2\"/>\n"
"    <eventcontext id=\"text\""
"                  style=\"fill:black;stroke:none;font-family:helvetica;font-style:normal;font-weight:normal;font-size:12px;\"/>"
"    <eventcontext id=\"nodes\"/>\n"
"    <eventcontext id=\"zoom\"/>\n"
"    <eventcontext id=\"select\"/>\n"
"  </group>\n"
"</sodipodi>\n";

#define PREFERENCES_SKELETON_SIZE (sizeof (preferences_skeleton) - 1)
