#define __PREFERENCES_SKELETON_H__

static const char preferences_skeleton[] =
"<sodipodi version=\"" VERSION "\">\n"
"  <style id=\"paint\""
"         style=\"fill:#7f7f7f;fill-opacity:1;fill-rule:evenodd;"
"                 stroke:#000000;stroke-opacity:1;stroke-width:1px;stroke-linejoin:miter;stroke-linecap:butt;\">\n"
"    <style id=\"shape\" style=\"stroke:none\">\n"
"      <style id=\"rect\"/>\n"
"      <style id=\"arc\"/>\n"
"      <style id=\"star\"/>\n"
"      <style id=\"spiral\"/>\n"
"    </style>\n"
"    <style id=\"freehand\" style=\"fill:none;\"/>\n"
"    <style id=\"calligraphic\" style=\"stroke:none;fill-rule:nonzero;\"/>\n"
"    <style id=\"text\""
"           style=\"fill:#000000;stroke:none;font-family:helvetica;font-style:normal;font-weight:normal;font-size:12px;\"/>"
"  </style>\n"
"  <interface id=\"toolboxes\">\n"
"    <interface id=\"file\" state=\"1\"/>\n"
"    <interface id=\"edit\" state=\"1\"/>\n"
"    <interface id=\"object\" state=\"1\"/>\n"
"    <interface id=\"selection\" state=\"0\"/>\n"
"    <interface id=\"draw\" state=\"1\"/>\n"
"    <interface id=\"zoom\" state=\"0\"/>\n"
"    <interface id=\"node\" state=\"0\"/>\n"
"  </interface>\n"
"  <group id=\"tools\">\n"
"    <group id=\"shapes\">\n"
"      <eventcontext id=\"star\" magnitude=\"6\"/>\n"
"    </group>\n"
"    <group id=\"freehand\">\n"
"      <eventcontext id=\"pen\" mode=\"drag\"/>\n"
"      <eventcontext id=\"dynamic\" mass=\"0.1\" drag=\"0.4\" angle=\"60\" width=\"0.4\"/>\n"
"    </group>\n"
"  </group>\n"
"</sodipodi>\n";

#define PREFERENCES_SKELETON_SIZE (sizeof (preferences_skeleton) - 1)
